#!/bin/bash
projectName="zds"
jiraUrl="https:\/\/naranja.atlassian.net\/browse\/"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    sed -i 'CHANGELOG.md' -e "s+http://+https://+g" 
    sed -i -r "s/\*\s($projectName\-[0-9]+)(.*)/\* \[\1\]($jiraUrl\1)\2/g" CHANGELOG.md
elif [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' 's+http://+https://+g' 'CHANGELOG.md'
    sed -i '' -E "s/\* ($projectName\-[0-9]+)(.*)/\* [\1\]($jiraUrl\1)\2/g" CHANGELOG.md
fi