FROM node:14.15.1 AS compile-image 

# Set working directory
WORKDIR /usr/src/app/app-ui

# Copy and install local npm packages
COPY package*.json ./

# Install global npm packages
RUN npm install -g @angular/cli@11.0.2 @angular-devkit/build-angular && npm install --save @angular/cli@11.0.2

EXPOSE 4201

CMD ["npm", "start"]