apiVersion: v1
kind: Service
metadata:
  name: \{{ template "app_chart.fullname" . }}
  labels:
    app: \{{ template "app_chart.name" . }}
    chart: \{{ template "app_chart.chart" . }}
    release: \{{ .Release.Name }}
    heritage: \{{ .Release.Service }}
spec:
  type: \{{ .Values.front.service.type }}
  ports:
    - port: \{{ .Values.front.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: \{{ template "app_chart.name" . }}
    release: \{{ .Release.Name }}
