apiVersion: v1
kind: Service
metadata:
  name: \{{ template "app_chart.fullname" . }}-varnish-proxy
  labels:
    app: \{{ template "app_chart.fullname" . }}-varnish-proxy
    chart: "\{{ .Chart.Name }}-\{{ .Chart.Version }}"
    release: "\{{ .Release.Name }}"
    heritage: "\{{ .Release.Service }}"
    host: "\{{ include "varnish.host" .}}"
spec:
  type: \{{ .Values.varnish.serviceType }}
  ports:
    - name: http
      port:  \{{ .Values.varnish.servicePort }}
      targetPort: \{{ .Values.varnish.containerPort }}
  selector:
    app: \{{ template "app_chart.fullname" . }}-varnish-proxy
