\{{- if .Values.varnish.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: \{{ .Release.Name }}-varnish-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: \{{ template "app_chart.fullname" . }}-varnish-proxy
  minReplicas: \{{ .Values.varnish.minReplicas }}
  maxReplicas: \{{ .Values.varnish.hpa.maxReplicas }}
  metrics:
  \{{- if .Values.varnish.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: \{{ .Values.varnish.hpa.cpu }}
  \{{- end }}
  \{{- if .Values.varnish.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: \{{ .Values.varnish.hpa.memory }}
  \{{- end }}
\{{- end }}
