const rollupGlobals = {
  'date-fns': 'date.fns',
  'codemirror': 'codemirror',
  'ng2-nouislider/src/nouislider': 'nouislider',
  'svg-pan-zoom': 'svg.pan.zoom',
  'tslib': 'tslib',
  'ramda': 'ramda',
  'file-saver': 'file-saver',
  'lodash': 'lodash',
  'rxjs': 'rxjs',
  'rxjs/operators': 'Rx.operators',

  'd3': 'd3',
  'd3-ease': 'd3.ease',
  'd3-interpolate': 'd3.interpolate',
  'd3-scale': 'd3.scale',
  'd3-selection': 'd3.selection',

  'hammerjs': 'hammerjs',

  'ngx-device-detector': 'ngx-device-detector',
  "ngx-modal-dialog": "ngx-modal-dialog",

  '@angular/animations': 'ng.animations',
  '@angular/core': 'ng.core',
  '@angular/common': 'ng.common',
  '@angular/common/http': 'ng.common',
  '@angular/forms': 'ng.forms',
  '@angular/http': 'ng.http',
  '@angular/router': 'ng.router',
  '@angular/platform-browser': 'ng.platformBrowser',
  '@angular/platform-server': 'ng.platformServer',
  '@angular/platform-browser-dynamic': 'ng.platformBrowserDynamic',
  '@angular/platform-browser/animations': 'ng.platformBrowser.animations',
  '@angular/core/testing': 'ng.core.testing',
  '@angular/common/testing': 'ng.common.testing',
  '@angular/http/testing': 'ng.http.testing',
  '@angular/material': 'ng.material',
  '@angular/cdk': 'ng.cdk',
  '@angular/cdk/portal': 'ng.cdk.portal',
  '@angular/cdk/coercion': 'ng.cdk.coercion',
  '@angular/cdk/layout': 'ng.cdk.layout',
  '@angular/cdk/platform': 'ng.cdk.platform',
  '@angular/cdk/testing': 'ng.cdk.testing',
  '@angular/cdk/overlay': 'ng.cdk.overlay',
  '@angular/material-examples': 'ng.materialExamples',

  '@ng-bootstrap/ng-bootstrap': 'ngb.ngb',
  '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module': 'ngb.tooltip',
  '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module': 'ngb.dropdown',
  '@ng-bootstrap/ng-bootstrap/popover/popover.module': 'ngb.popover',
};

module.exports = rollupGlobals;
