- request:
    url: ^/rest/v2/region/europe$
    method: GET
  response:
  - status: 200
    latency: 100
    headers:
      content-type: application/json
      access-control-allow-origin: "*"
      access-control-allow-method: "*"
    file: restcountries.eu/rest/v2/region/europe/index.json