version: "3"

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./data/certs/demo.local.crt:/etc/nginx/ssl/demo.local.crt
      - ./data/certs//demo.local.key:/etc/nginx/ssl/demo.local.key
    depends_on:
      - varnish
      - front-naranja-web
    links:
      - front-naranja-web
      - varnish
    restart: always

  front-naranja-web:
    build:
      context: ../
      dockerfile: Dockerfile
    #network_mode: bridge
    container_name: front-naranja-web
    expose:
      - 80
      - 443
      - 4200
    ports:
      - "4200:4200"
    tty: true

  varnish:
    image: "tripviss/varnish"
    container_name: varnish
    expose:
      - 6081
    environment:
      VARNISH_VCL: "/etc/varnish/varnish.vcl"
      VARNISH_MEMORY: "3072M"
    volumes:
      - ./varnish/varnish.vcl:/etc/varnish/varnish.vcl
    depends_on:
      - front-naranja-web
